AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Unit Admin API - Secured from DevUserPool

Globals:
  Function:
    Timeout: 5
  Api:
    Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        AllowOrigin: "'*'"
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
            Access-Control-Allow-Methods: "'POST, OPTIONS'"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
            Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
            Access-Control-Allow-Methods: "'POST, OPTIONS'"
Parameters:

  Authentication:
    Type: String
    Description: Disable Authentication (True) or Leave It (False)
    Default: "false"
    
Resources:
  AdminUnitAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
  UnitAdminAPI:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{operation+}
            Method: ANY
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevUnits
        - DynamoDBCrudPolicy:
            TableName: DevMajors
        - DynamoDBCrudPolicy:
            TableName: DevSpecializations
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  AdminUnitAPI:
    Description: Admin unit api
    Value: !Ref AdminUnitAPI