AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Unit Admin API - Secured from DevUserPool

Globals:
  Function:
    Timeout: 5

Parameters:

  Authentication:
    Type: String
    Description: Disable Authentication (True) or Leave It (False)
    Default: "false"
    
Resources:
  AdminUnitAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        AllowOrigin: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
              Access-Control-Allow-Methods: "'OPTIONS,POST'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
              Access-Control-Allow-Methods: "'OPTIONS,POST'"
  AddUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /addunit
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevUnits
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./addunit
      Dockerfile: Dockerfile
  RemoveUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /removeunit
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevUnits
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./removeunit
      Dockerfile: Dockerfile
  UpdateUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /updateunit
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevUnits
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./updateunit
      Dockerfile: Dockerfile
  AddMajorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /addmajor
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevMajors
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./addmajor
      Dockerfile: Dockerfile
  UpdateMajorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /updatemajor
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevMajors
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./updatemajor
      Dockerfile: Dockerfile
  RemoveMajorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /removemajor
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevMajors
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./removemajor
      Dockerfile: Dockerfile
  AddSpecFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /addspec
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevSpecializations
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./addspec
      Dockerfile: Dockerfile
  UpdateSpecFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /updatespec
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevSpecializations
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./updatespec
      Dockerfile: Dockerfile
  RemoveSpecFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /removespec
            Method: POST
            RestApiId: !Ref AdminUnitAPI
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevSpecializations
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./removespec
      Dockerfile: Dockerfile

Outputs:
  AdminUnitAPI:
    Description: Admin unit api
    Value: !Ref AdminUnitAPI