image: atlassian/default-image:2
pipelines:
  pull-requests:
    dev-sprint:
      - step:
          script:
            - echo "hello world"
    master:
      - step:
          image: atlassian/pipelines-awscli
          script: