image: atlassian/default-image:2
pipelines:
  pull-requests:
    dev-sprint:
      - step:
          image: atlassian/pipelines-awscli
          script:
            - echo "Setting Up AWS CLI"
            - aws configure set aws_access_key_id $PipelineAccessKey
            - aws configure set aws_secret_access_key $PipelineSecretKey
            - aws configure set default.region ap-southeast-2
            - aws configure set region ap-southeast-2
            - echo "Deploying Dev Database"
            - aws cloudformation deploy --template-file "./Infrastructure Templates/DevDatabases.yaml" --stack-name DevDB
    master:
      - step:
          image: atlassian/pipelines-awscli
          script:
            - echo "Setting Up AWS CLI"
            - aws configure set aws_access_key_id $PipelineAccessKey
            - aws configure set aws_secret_access_key $PipelineSecretKey
            - aws configure set default.region ap-southeast-2
            - aws configure set region ap-southeast-2
            - echo "Deploying Dev Database"
            - aws cloudformation deploy --template-file "./Infrastructure Templates/DevDatabases.yaml" --stack-name DevDB