version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CSVParser"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ta1vvir9jjtd"
s3_prefix = "CSVParser"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Authentication=\"true\""
image_repositories = ["CSVParser=363837338544.dkr.ecr.ap-southeast-2.amazonaws.com/curtinmedicalcourseplanner/csvparser"]
