AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CSVParser
  
  Parse CSV to effect DB

Globals:
  Function:
    Timeout: 180 # Way Bigger Timeout As were doing a long process

Parameters:

  Authentication:
    Type: String
    Description: Disable Authentication (True) or Leave It (False)
    Default: "true"

Resources:
  CSVParser:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{operation+}
            Method: ANY
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./CSVParser
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
