AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CareersAdminAPI

  Sample SAM Template for CareersAdminAPI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  #Example
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.8-v1

    AddCareerFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          AddCareer:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /addcareer
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./addcareer
        DockerTag: python3.8-v1

    AddTraitFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          AddTrait:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /addtrait
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./addtrait
        DockerTag: python3.8-v1

    CareerCSVFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          CareerCSV:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /careerCSV
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./careercsv
        DockerTag: python3.8-v1

    DeleteCareerFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          DeleteCareer:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /deletecareer
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./deletecareer
        DockerTag: python3.8-v1
              
    DeleteTraitFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          DeleteTrait:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /deletetrait
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./deletetrait
        DockerTag: python3.8-v1

    TraitCSVFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          TraitCSV:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /traitCSV
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./traitcsv
        DockerTag: python3.8-v1

    UpdateCareerFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          UpdateCareer:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /updatecareer
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./updatecareer
        DockerTag: python3.8-v1

    UpdateTraitFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        PackageType: Image
        Events:
          UpdateTrait:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /updatetrait
              Method: POST
      Metadata:
        Dockerfile: Dockerfile
        DockerContext: ./updatetrait
        DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  #Example
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  #APIs
  AddCareerApi:
    Description: "API Gateway endpoint URL for Prod stage for Add Career function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addcareer/"
  AddTraitApi:
    Description: "API Gateway endpoint URL for Prod stage for Add Trait function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addtrait/"
  CareerCSVApi:
    Description: "API Gateway endpoint URL for Prod stage for Career CSV function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/careercsv/"
  DeleteCareerApi:
    Description: "API Gateway endpoint URL for Prod stage for Delete Career function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deletecareer/"
  DeleteTraitApi:
    Description: "API Gateway endpoint URL for Prod stage for Delete Trait function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deletetrait/"
  TraitCSVApi:
    Description: "API Gateway endpoint URL for Prod stage for Trait CSV function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/traitcsv/"
  UpdateCareerApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Career function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updatecareer/"
  UpdateTraitApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Trait function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updatetrait/"

  #Functions
  AddCareerFunction:
    Description: "Add Career Lambda Function ARN"
    Value: !GetAtt AddCareerFunction.Arn
  AddTraitFunction:
    Description: "Add Trait Lambda Function ARN"
    Value: !GetAtt AddTraitFunction.Arn
  CareerCSVFunction:
    Description: "Career CSV Lambda Function ARN"
    Value: !GetAtt CareerCSVFunction.Arn
  DeleteCareerFunction:
    Description: "Delete Career Lambda Function ARN"
    Value: !GetAtt DeleteCareerFunction.Arn
  DeleteTraitFunction:
    Description: "Delete Trait Lambda Function ARN"
    Value: !GetAtt DeleteTraitFunction.Arn
  TraitCSVFunction:
    Description: "Trait CSV Lambda Function ARN"
    Value: !GetAtt TraitCSVFunction.Arn
  UpdateCareerFunction:
    Description: "Update Career Lambda Function ARN"
    Value: !GetAtt UpdateCareerFunction.Arn
  UpdateTraitFunction:
    Description: "Upate Trait Lambda Function ARN"
    Value: !GetAtt Update TraitFunction.Arn

  #Function IAM Roles
  AddCareerFunctionIamRole:
    Description: "Implicit IAM Role created for Add Career function"
    Value: !GetAtt AddCareerFunction.Arn
  AddTraitFunctionIamRole:
    Description: "Implicit IAM Role created for Add Trait function"
    Value: !GetAtt AddTraitFunction.Arn
  CareerCSVFunctionIamRole:
    Description: "Implicit IAM Role created for Career CSV function"
    Value: !GetAtt CareerCSVFunction.Arn
  DeleteCareerFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Career function"
    Value: !GetAtt DeleteCareerFunction.Arn
  DeleteTraitFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Trait function"
    Value: !GetAtt DeleteTraitFunction.Arn
  TraitCSVFunctionIamRole:
    Description: "Implicit IAM Role created for Trait CSV function"
    Value: !GetAtt TraitCSVFunction.Arn
  UpdateCareerFunctionIamRole:
    Description: "Implicit IAM Role created for Update Career function"
    Value: !GetAtt UpdateCareerFunction.Arn
  UpdateTraitFunctionIamRole:
    Description: "Implicit IAM Role created for Update Trait function"
    Value: !GetAtt UpdateTraitFunction.Arn
  
