AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Careers Admin API

#Author: Matthew Loe
#Student Id: 19452425
#Date Created: 17/05/2021
#Date Last Modified: 15/08/2021

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Parameters:
  Authentication:
    Type: String
    Description: Disable Authentication (True) or Leave It (False)
    Default: "False"

Resources:
  #API and Functions
  AddCareerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        AddCareer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /addcareer
            Method: POST
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevCareer
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./addcareer
      DockerTag: python3.8-v1

  AddTraitFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        AddTrait:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /addtrait
            Method: POST
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevTrait
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./addtrait
      DockerTag: python3.8-v1

  DeleteCareerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        DeleteCareer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /deletecareer
            Method: POST
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevCareer
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./deletecareer
      DockerTag: python3.8-v1
            
  DeleteTraitFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        DeleteTrait:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /deletetrait
            Method: POST
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevTrait
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./deletetrait
      DockerTag: python3.8-v1

  UpdateCareerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        UpdateCareer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /updatecareer
            Method: POST
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevCareer
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./updatecareer
      DockerTag: python3.8-v1

  UpdateTraitFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        UpdateTrait:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /updatetrait
            Method: POST
      Environment:
        Variables:
          DisableAuthentication: !Ref Authentication
      Policies:
        - DynamoDBCrudPolicy:
            TableName: DevTrait
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./updatetrait
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  
  #APIs
  AddCareerApi:
    Description: "API Gateway endpoint URL for Prod stage for Add Career function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addcareer/"
  AddTraitApi:
    Description: "API Gateway endpoint URL for Prod stage for Add Trait function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addtrait/"
  DeleteCareerApi:
    Description: "API Gateway endpoint URL for Prod stage for Delete Career function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deletecareer/"
  DeleteTraitApi:
    Description: "API Gateway endpoint URL for Prod stage for Delete Trait function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deletetrait/"
  UpdateCareerApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Career function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updatecareer/"
  UpdateTraitApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Trait function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updatetrait/"

  #Functions
  AddCareerFunction:
    Description: "Add Career Lambda Function ARN"
    Value: !GetAtt AddCareerFunction.Arn
  AddTraitFunction:
    Description: "Add Trait Lambda Function ARN"
    Value: !GetAtt AddTraitFunction.Arn
  DeleteCareerFunction:
    Description: "Delete Career Lambda Function ARN"
    Value: !GetAtt DeleteCareerFunction.Arn
  DeleteTraitFunction:
    Description: "Delete Trait Lambda Function ARN"
    Value: !GetAtt DeleteTraitFunction.Arn
  UpdateCareerFunction:
    Description: "Update Career Lambda Function ARN"
    Value: !GetAtt UpdateCareerFunction.Arn
  UpdateTraitFunction:
    Description: "Upate Trait Lambda Function ARN"
    Value: !GetAtt UpdateTraitFunction.Arn

  #Function IAM Roles
  AddCareerFunctionIamRole:
    Description: "Implicit IAM Role created for Add Career function"
    Value: !GetAtt AddCareerFunction.Arn
  AddTraitFunctionIamRole:
    Description: "Implicit IAM Role created for Add Trait function"
    Value: !GetAtt AddTraitFunction.Arn
  DeleteCareerFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Career function"
    Value: !GetAtt DeleteCareerFunction.Arn
  DeleteTraitFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Trait function"
    Value: !GetAtt DeleteTraitFunction.Arn
  UpdateCareerFunctionIamRole:
    Description: "Implicit IAM Role created for Update Career function"
    Value: !GetAtt UpdateCareerFunction.Arn
  UpdateTraitFunctionIamRole:
    Description: "Implicit IAM Role created for Update Trait function"
    Value: !GetAtt UpdateTraitFunction.Arn
  
