AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for UnitAPI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.8-v1
  
  getallspecs:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        getallspecs:
          Type: Api
          Properties:
            Path: /getallspecs
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./getallspecs
      DockerTag: python3.8-v1
  
  getallmajors:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        getallmajors:
          Type: Api
          Properties:
            Path: /getallmajors
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./getallmajors
      DockerTag: python3.8-v1

  getallunits:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events: 
        getallunits:
          Type: Api
          Properties:
            Path: /getallunits
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./getallunits
      DockerTag: python3.8-v1
  
  getmajor:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        getmajor:
          Type: Api
          Properties:
            Path: /getmajor
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./getmajor
      DockerTag: python3.8-v1

  getspec:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        getspec:
          Type: Api
          Properties:
            Path: /getspec
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./getspec
      DockerTag: python3.8-v1

  getunit:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        getunit:
          Type: Api
          Properties:
            Path: /getunit
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./getunit
      DockerTag: python3.8-v1
  searchmajor:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        searchmajor:
          Type: Api
          Properties:
            Path: /searchmajor
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./searchmajor
      DockerTag: python3.8-v1
  searchspec:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        searchspec:
          Type: Api
          Properties:
            Path: /searchspec
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./searchspec
      DockerTag: python3.8-v1
  searchunit:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        searchunit:
          Type: Api
          Properties:
            Path: /searchunit
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./searchunit
      DockerTag: Python3.8-v1
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
