AWSTemplateFormatVersion: '2010-09-09'
Description: Template that creates Dev DBs.
Resources:
  DevUnitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "UnitCode"
          AttributeType: "S"
      BillingMode: "PROVISIONED"
      KeySchema:
        - AttributeName: "UnitCode"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "DevUnits"
  DevMajorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "MajorCode"
          AttributeType: "S"
      BillingMode: "PROVISIONED"
      KeySchema:
        - AttributeName: "MajorCode"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "DevMajors"
  DevSpecializationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "SpecializationCode"
          AttributeType: "S"
      BillingMode: "PROVISIONED"
      KeySchema:
        - AttributeName: "SpecializationCode"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "DevSpecializations"
  DevTraitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Name"
          AttributeType: "S"
      BillingMode: "PROVISIONED"
      KeySchema:
        - AttributeName: "Name"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "DevTraits"
  DevCareerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "CareerName"
          AttributeType: "S"
      BillingMode: "PROVISIONED"
      KeySchema:
        - AttributeName: "CareerName"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "DevCareers"

Outputs:
  DevUnitsTable:
    Description: "Dev Units (1 R/W Unit - SLOW)"
    Value: !Ref DevUnitsTable
  DevMajorTable:
    Description: "Dev Majors (1 R/W Unit - SLOW)"
    Value: !Ref DevMajorTable
  DevSpecializationTable:
    Description: "Dev Specializations (1 R/W Unit - SLOW)"
    Value: !Ref DevSpecializationTable
  DevTraitTable:
    Description: "Dev Traits (1 R/W Unit - SLOW)"
    Value: !Ref DevTraitTable
  DevCareerTable:
    Description: "Dev Careers (1 R/W Unit - SLOW)"
    Value: !Ref DevCareerTable