AWSTemplateFormatVersion: '2010-09-09'
Description: Template that creates Dev DBs.
Resources:
  DevUnitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "UnitCode"
          AttributeType: "S"
      BillingMode: "PROVISIONED"
      KeySchema:
        - AttributeName: "UnitCode"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "DevUnits"

Outputs:
  DevDB:
    Description: "Dev Units"
    Value: !Ref DevUnitsTable