AWSTemplateFormatVersion: "2010-09-09"
Description: Template that creates Dev DBs.
Resources:
  UnitAdminRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: curtinmedicalcourseplanner/unitadmin
  CareerAdminRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: curtinmedicalcourseplanner/careeradmin
Outputs:
  CareerAdminRepository:
    Description: Arn Value For Repository
    Value: !GetAtt CareerAdminRepository.Arn