AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Resources:
  DevUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
      AliasAttributes:
        - phone_number
        - email
        - preferred_username
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: True
        DeviceOnlyRememberedOnUserPrompt: True
      MfaConfiguration: "OFF" # MFA cost money, we can suggest it at the end of the capstone
      UserPoolName: "DevStaffUserPool"
  DevLoginClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref DevUserPool
      CallbackURLs:
        - http://localhost:3000
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid
      ClientName: CapstoneDevLogin
      SupportedIdentityProviders:
        - COGNITO
  DevLoginPage:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: curtincapstone3dev
      UserPoolId: !Ref DevUserPool

  ProdUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
      AliasAttributes:
        - phone_number
        - email
        - preferred_username
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: True
        DeviceOnlyRememberedOnUserPrompt: True
      MfaConfiguration: "OFF" # MFA cost money, we can suggest it at the end of the capstone
      UserPoolName: "ProdStaffUserPool"
  ProdLoginClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ProdUserPool
      CallbackURLs:
        - http://localhost:3000
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid
      ClientName: CapstoneProdLogin
      SupportedIdentityProviders:
        - COGNITO
  ProdLoginPage:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: curtincapstone3prod
      UserPoolId: !Ref ProdUserPool

Outputs:
  DevUserPool:
    Description: "The Dev Pool"
    Value: !Ref DevUserPool
  DevUserClient:
    Description: "The Dev User Client"
    Value: !Ref DevLoginClient
  DevLoginPage:
    Description: "The Dev Login Page"
    Value: !Ref DevLoginPage
  ProdUserPool:
    Description: "Prod Pool"
    Value: !Ref ProdUserPool
  ProdUserClient:
    Description: "The Prod User Client"
    Value: !Ref ProdLoginClient
  ProdLoginPage:
    Description: "The Prod Login Page"
    Value: !Ref ProdLoginPage